import type { Metadata } from "next";
import "@/style/globals.css";
import { NavBar } from "@/Components";
import NextTopLoader from "nextjs-toploader";
import { SessionAuthProvider, PageTransition } from "@/context";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <NextTopLoader />
        <PageTransition >
          <SessionAuthProvider >
            <NavBar />
            {children}
          </SessionAuthProvider>
        </PageTransition>
      </body>
    </html>
  );
}
